"""
Claims made by the General AC-MOT manuscript, each tied to registry keys (scripts/evidence.py)
or to a named evidence file. Used by check_numbers.py to write EVIDENCE_MATRIX.md and
CLAIMS_AND_SOURCES.md. A claim without a numeric key names the file that supports it.

Fields: id, section, claim, keys (value + interval come from the registry), files (extra
evidence files for non-numeric claims), experiment, dataset, detector, tracker, metric,
status, safe wording.
"""

F = "research/final/"
EV = "research/paper_split/evidence/legacy/"

CLAIMS = [
    # ---------------------------------------------------------------- Stage 1
    dict(id="S1-1", section="Results 6.1 / Abstract", claim="AC-MOT raised HOTA over the static default on VisDrone test-dev",
         keys=["s1.base.HOTA", "s1.q.HOTA", "s1.qb.dHOTA"], experiment="locked one-shot three-system comparison",
         dataset="VisDrone2019-MOT test-dev (17 seq.)", detector="YOLOv8n", tracker="ByteTrack (default vs tuned)",
         metric="HOTA", status="held-out, custom class-agnostic protocol",
         wording="raised HOTA from 28.43 to 33.84 under a custom class-agnostic protocol; not the official VisDrone toolkit"),
    dict(id="S1-2", section="Results 6.1", claim="AC-MOT won on every test-dev sequence", keys=["s1.qb.wtl"],
         experiment="per-sequence HOTA", dataset="VisDrone2019-MOT test-dev", detector="YOLOv8n", tracker="ByteTrack",
         metric="W/T/L (HOTA)", status="held-out", wording="won on all 17 sequences"),
    dict(id="S1-3", section="Results 6.1", claim="MOTA and IDF1 gains over the static default",
         keys=["s1.qb.dMOTA", "s1.qb.dIDF1"], experiment="locked comparison", dataset="VisDrone2019-MOT test-dev",
         detector="YOLOv8n", tracker="ByteTrack", metric="MOTA, IDF1", status="held-out", wording="as measured, with intervals"),
    dict(id="S1-4", section="Results 6.1", claim="The gain came mostly from recall; IDS reduction not significant",
         keys=["s1.qb.dFN", "s1.qb.dFP", "s1.qb.dIDS_reduction"], experiment="locked comparison",
         dataset="VisDrone2019-MOT test-dev", detector="YOLOv8n", tracker="ByteTrack", metric="FN, FP, IDS",
         status="held-out", wording="FN fell, FP rose; IDS interval contains zero"),
    dict(id="S1-5", section="Results 6.1", claim="Against the hand-designed controller: higher HOTA, more identity switches",
         keys=["s1.qh.dHOTA", "s1.q.IDS", "s1.heur.IDS", "s1.qh.dIDS_reduction"], experiment="locked comparison",
         dataset="VisDrone2019-MOT test-dev", detector="YOLOv8n", tracker="ByteTrack (tuned)", metric="HOTA, IDS",
         status="held-out", wording="did not dominate the earlier controller on every metric"),
    dict(id="S1-6", section="Results 6.1 / Abstract", claim="Frozen AC-MOT transferred to UAVDT without retuning",
         keys=["uav.qb.dHOTA", "uav.qb.wtl"], experiment="frozen zero-retuning run", dataset="UAVDT test (20 seq.)",
         detector="YOLOv8n", tracker="ByteTrack", metric="HOTA", status="held-out transfer, UAVDT adapter",
         wording="+4.305 HOTA without retuning (interval from the freeze record text)"),
    dict(id="S1-7", section="Results 6.1", claim="Stage-1 throughput excludes decoding and varies between sessions",
         keys=["s1.q.FPS", "t4.decode", "t4.playfps"], files=[EV + "NEW_ACMOT_COMPONENT_ABLATION.csv", EV + "OPERATING_NMS_SWEEP.csv"],
         experiment="T4 timing", dataset="VisDrone test-dev", detector="YOLOv8n", tracker="ByteTrack", metric="FPS, ms",
         status="timing", wording="processing throughput on decoded frames; same configuration measured 37.92 vs 44.78 FPS in two sessions"),
    # ---------------------------------------------------------------- attribution
    dict(id="AT-1", section="Results 6.2 / Abstract / Intro", claim="A matched static operating point reproduces the controller on test-dev",
         keys=["ms.a0.HOTA", "s1.q.HOTA", "ms.dHOTA", "ms.dMOTA", "ms.dIDF1", "ms.dIDS_reduction"],
         experiment="post hoc matched-static run", dataset="VisDrone2019-MOT test-dev", detector="YOLOv8n",
         tracker="ByteTrack (tuned)", metric="HOTA, MOTA, IDF1, IDS", status="post hoc attribution",
         wording="reached the same held-out accuracy within the resolution of the test; post hoc, used for attribution only"),
    dict(id="AT-2", section="Results 6.2 / Intro", claim="On validation the gain decomposes into tracker profile, calibrated operating point and switching",
         keys=["val.d_tracker", "val.d_operating", "val.d_switch"], experiment="component ablations",
         dataset="VisDrone2019-MOT val (7 seq.)", detector="YOLOv8n", tracker="ByteTrack", metric="HOTA",
         status="validation (development)", wording="on validation: +1.03 tracker, +5.21 operating point, +0.03 switching"),
    dict(id="AT-3", section="Results 6.2", claim="The calibrated controller hardly switched",
         keys=["val.q.res", "val.q.conf", "val.q.nms"], experiment="component ablation A3", dataset="VisDrone val",
         detector="YOLOv8n", tracker="ByteTrack", metric="mean settings", status="validation",
         wording="mean input 957 px, mean confidence 0.34, constant NMS 0.35"),
    # ---------------------------------------------------------------- transfer barrier
    dict(id="TB-1", section="Results 6.3", claim="Stage-1 SCI thresholds do not carry over to another pipeline",
         keys=["u2.sci_lo", "u2.sci_hi", "u2.bound_lo", "u2.bound_hi", "u2.dHOTA"], experiment="U2MOT recalibrated controller",
         dataset="VisDrone val / test-dev", detector="YOLOX-X (U2MOT)", tracker="U2MOT", metric="SCI range, HOTA",
         status="held-out (test-dev), U2MOT protocol, post hoc rescore", wording="every frame would fall into the hardest tier; recalibrated controller changed HOTA by -0.06 (interval contains 0)"),
    dict(id="TB-2", section="Results 6.3 / Abstract / Intro", claim="One raw threshold gives 0 to 6 catastrophic sequences across four detectors",
         keys=["raw.yolov8.cat", "raw.rtdetr.cat", "raw.retinanet.cat", "raw.fasterrcnn.cat"],
         experiment="host alone with raw 0.25", dataset="VisDrone2019-MOT val", detector="YOLOv8n, RT-DETR-L, RetinaNet, Faster R-CNN",
         tracker="ByteTrack (library default)", metric="sequences with MOTA < 0", status="development split, internal protocol",
         wording="between 0 and 6 sequences with negative MOTA"),
    dict(id="TB-3", section="Results 6.3", claim="Score streams differ in density and in the location of the confident band",
         keys=[], files=["figures/fig_data.json (computed from release assets v7-dev-assets-1 and sci-v7f-unseen-1)"],
         experiment="descriptive statistics of cached detector streams", dataset="VisDrone val, 736 px",
         detector="four detectors", tracker="--", metric="candidates/frame, median sigma(t2)", status="descriptive",
         wording="106 to 323 candidates per frame; median sigma(t2) 0.27 to 0.76"),
    dict(id="TB-4", section="Results 6.3 / Abstract / Intro", claim="Halving detector scores drives two trackers to zero HOTA",
         keys=["cal.byoff.scale05.native", "cal.oc.scale05.native"], experiment="calibration-shift stress",
         dataset="MOT17 val-half", detector="YOLOX-X (published)", tracker="ByteTrack (official), OC-SORT", metric="HOTA",
         status="development hosts", wording="no detection reaches the fixed thresholds"),
    dict(id="TB-5", section="Results 6.3 / Intro", claim="The always-on training-free predecessor harmed two strong published trackers",
         keys=["v6.sparse.dHOTA", "v6.boost.dHOTA"], experiment="V6-TF external transfer", dataset="MOT17 val-half",
         detector="YOLOX-X", tracker="SparseTrack, BoostTrack", metric="HOTA", status="post-freeze (V6-TF)",
         wording="cost 4.15 and 5.89 HOTA; motivated host awareness"),
    dict(id="TB-6", section="Results 6.3", claim="Earlier designs: histogram normalizer + ratio gate, order-only gate, VisDrone-selected constants",
         keys=[], files=["research/context/FROZEN_VERSIONS.md", "research/context/DECISIONS.md"], experiment="design history",
         dataset="--", detector="--", tracker="--", metric="--", status="history", wording="qualitative"),
    # ---------------------------------------------------------------- method
    dict(id="M-1", section="Method 4.3-4.13", claim="Algorithm description follows the frozen code",
         keys=["const.window", "const.regime", "const.minlogits", "const.remap", "const.margin", "const.cap"],
         files=["acmot_v7.py (V7Layer.step)", "online_calibration.py (nested_otsu)", "configs/universal_acmot_policy_v7.json"],
         experiment="code", dataset="--", detector="--", tracker="--", metric="--", status="frozen code (tag universal-acmot-v7-freeze)",
         wording="as implemented"),
    dict(id="M-2", section="Method 4.13 / 4.4", claim="The policy contains no model names; the host contract has no identity field",
         keys=[], files=["tests/test_v7_adaptive_layer.py::test_no_detector_tracker_dataset_or_sequence_names_in_layer",
                         "tests/test_v7_adaptive_layer.py::test_host_contract_has_no_identity_field"],
         experiment="unit tests (57 passed, 2 skipped without caches)", dataset="--", detector="--", tracker="--", metric="--",
         status="tests", wording="checked by unit test"),
    dict(id="M-3", section="Method 4.9 / 4.15", claim="Causality, no-raise in clean regime, affine invariance of regime decisions on frozen V7f",
         keys=[], files=["tests/test_v7f_paper2_claims.py (25 passed)"], experiment="unit tests on the frozen V7f configuration",
         dataset="--", detector="--", tracker="--", metric="--", status="tests", wording="asserted by unit tests"),
    dict(id="M-4", section="Method 4.2", claim="General AC-MOT compute request is constant (736 px)",
         keys=["vd.yolov8.g1.res", "vd.yolov8.g1.switches"], files=["configs/general_acmot_g1.json"],
         experiment="G1 operating record", dataset="VisDrone val", detector="all", tracker="all", metric="resolution, switches",
         status="frozen G1", wording="behaviourally V7f at a fixed detector setting"),
    dict(id="M-5", section="Method 4.12", claim="The motion rule was inactive in every MOT17 and external experiment",
         keys=[], files=[F + "recent/ctwix/audit_*.json (motion_ratio always 1, match constant)", F + "V7_EXTERNAL_TRANSFER.md"],
         experiment="audit logs", dataset="MOT17, KITTIMOTS, DanceTrack", detector="--", tracker="external", metric="--",
         status="audit", wording="inactive"),
    dict(id="M-6", section="Protocol", claim="All files in the V7f and G1 locks match their hashes at the evidence snapshot",
         keys=[], files=["research/V7_POLICY_LOCK.json", "research/GENERAL_ACMOT_G1_LOCK.json"], experiment="hash check",
         dataset="--", detector="--", tracker="--", metric="--", status="verified by check_numbers.py", wording="as stated"),
    # ---------------------------------------------------------------- development results
    dict(id="D-1", section="Results 6.4", claim="General AC-MOT raises HOTA on VisDrone val for both development detectors",
         keys=["vd.yolov8.int.dHOTA", "vd.rtdetr.int.dHOTA", "vd.pool.off.dHOTA"], experiment="NATIVE+MEDIUM vs V7f+MEDIUM",
         dataset="VisDrone2019-MOT val (7 seq.)", detector="YOLOv8n, RT-DETR-L", tracker="ByteTrack", metric="HOTA",
         status="development", wording="development evidence"),
    dict(id="D-2", section="Results 6.4", claim="RT-DETR-L: MOTA up, catastrophic sequences 5 to 0, FN up",
         keys=["vd.rtdetr.int.dMOTA", "vd.rtdetr.base.cat", "vd.rtdetr.g1.cat", "vd.rtdetr.int.dFN"],
         experiment="as D-1", dataset="VisDrone val", detector="RT-DETR-L", tracker="ByteTrack", metric="MOTA, FN, catastrophic",
         status="development", wording="at the price of more false negatives"),
    dict(id="D-3", section="Results 6.4", claim="KITTI: two-stage hosts gain MOTA/IDF1 with RT-DETR-L; OC-SORT gains with YOLOv8n; YOLOv8n two-stage MOTA cost",
         keys=["kitd.rtdetr.by.dMOTA", "kitd.rtdetr.bot.dMOTA", "kitd.yolov8.oc.dHOTA", "kitd.yolov8.by.dMOTA", "kitd.yolov8.bot.dMOTA"],
         experiment="KITTI development matrix", dataset="KITTI tracking training (21 seq.)", detector="YOLOv8n, RT-DETR-L",
         tracker="ByteTrack, BoT-SORT, OC-SORT", metric="HOTA, MOTA", status="development", wording="development evidence"),
    dict(id="D-4", section="Results 6.4", claim="MOT17: transparent on two-stage hosts, gain on OC-SORT",
         keys=["mot.st.dHOTA", "mot.byoff.dHOTA", "mot.bt.identical", "mot.byul.identical", "mot.oc.dHOTA"],
         experiment="MOT17 development hosts", dataset="MOT17 val-half", detector="YOLOX-X (published)",
         tracker="SparseTrack, BoostTrack, ByteTrack, OC-SORT", metric="HOTA", status="development", wording="development evidence"),
    # ---------------------------------------------------------------- transfer
    dict(id="X-1", section="Transfer 7.1 / Abstract", claim="Frozen V7f improves the predeclared external tracker PD-SORT",
         keys=["ext.pd.base.HOTA", "ext.pd.dHOTA", "ext.pd.dMOTA", "ext.pd.dIDF1"], experiment="predeclared external system",
         dataset="MOT17 val-half", detector="YOLOX-X (released by PD-SORT authors)", tracker="PD-SORT", metric="HOTA, MOTA, IDF1",
         status="predeclared external, internal TrackEval", wording="reproduction equal to the authors' released output; not a test-server number"),
    dict(id="X-2", section="Transfer 7.1", claim="Hybrid-SORT output identical with and without the layer",
         keys=["ext.hy.dHOTA"], experiment="predeclared external system", dataset="MOT17 val-half", detector="YOLOX-X",
         tracker="Hybrid-SORT", metric="HOTA", status="predeclared external", wording="identical output"),
    dict(id="X-3", section="Transfer 7.1", claim="Post-freeze external trackers: mixed results, one significant loss",
         keys=["ctx.mot.dHOTA", "ctx.kcar.dHOTA", "ctx.kped.dHOTA", "ctx.dance.dHOTA", "tt.dance.dHOTA"],
         experiment="post-freeze preregistered systems", dataset="MOT17, KITTIMOTS val, DanceTrack val",
         detector="released detections (YOLOX-X, PermaTrack, DanceTrack sets)", tracker="C-TWiX, TrackTrack", metric="HOTA",
         status="post-freeze external", wording="no gain; C-TWiX KITTI car significant loss; TrackTrack difference negligible"),
    dict(id="X-4", section="Transfer 7.1", claim="TOPICTrack reproduction failed and is excluded", keys=["tp.mot.base.HOTA", "tp.mot.refHOTA"],
         experiment="post-freeze system", dataset="MOT17", detector="YOLOX-X", tracker="TOPICTrack", metric="HOTA",
         status="excluded", wording="excluded from main results"),
    dict(id="X-5", section="Transfer 7.1", claim="Development trackers BoT-SORT and OC-SORT on VisDrone (host compatibility)",
         keys=["bot.yolov8.int.dHOTA", "bot.rtdetr.int.dHOTA", "oc.yolov8.int.dHOTA", "oc.rtdetr.int.dHOTA", "oc.yolov8.base.Recall"],
         experiment="G1 host tests", dataset="VisDrone val", detector="YOLOv8n, RT-DETR-L", tracker="BoT-SORT, OC-SORT",
         metric="HOTA", status="development trackers", wording="host compatibility, not unseen-tracker transfer"),
    dict(id="X-6", section="Transfer 7.2 / Abstract", claim="General AC-MOT improves an unseen detector (RetinaNet) under a lock written before evaluation",
         keys=["rn.by.736.int.dHOTA", "rn.by.736.off.dHOTA", "bot.retinanet.int.dHOTA", "bot.retinanet.off.dHOTA", "rn.lock.status"],
         files=["research/TRANSFER_LOCK_RETINANET_G1.json"], experiment="locked unseen-detector transfer",
         dataset="VisDrone2019-MOT val (development sequences)", detector="RetinaNet R50-FPN v2", tracker="ByteTrack, BoT-SORT",
         metric="HOTA", status="unseen detector, development sequences",
         wording="a detector family not used in developing V7f, locked before evaluation, evaluated on development sequences"),
    dict(id="X-7", section="Transfer 7.3", claim="DanceTrack is the only dataset no development run used", keys=[],
         files=[F + "V7_PAPER_CLAIMS.md", F + "V7_RECENT_EXTERNAL_PROTOCOL.md"], experiment="protocol", dataset="DanceTrack val",
         detector="--", tracker="--", metric="--", status="protocol", wording="as stated"),
    dict(id="X-8", section="Transfer 7.4 / Abstract", claim="Calibration shift: 7 of 14 conditions significant recoveries, none significant degradation",
         keys=["cal.n", "cal.rec", "cal.deg", "cal.byoff.scale05.v7f", "cal.oc.scale05.v7f"], experiment="calibration-shift bootstrap",
         dataset="MOT17 val-half", detector="YOLOX-X", tracker="ByteTrack (2 settings), OC-SORT, BoostTrack", metric="HOTA",
         status="development hosts", wording="robustness, not held-out generalization"),
    # ---------------------------------------------------------------- ablation, runtime, boundary
    dict(id="A-1", section="Ablation 8", claim="Pass-through reproduces the hosts exactly",
         keys=["abl.passthrough.identical", "abl.passthrough.cells", "abl.passthrough.byte"], experiment="NATIVE vs BASELINE",
         dataset="MOT17 val-half", detector="YOLOX-X", tracker="development hosts", metric="all metrics", status="development",
         wording="identical; byte-identical replays for SparseTrack and BoostTrack"),
    dict(id="A-2", section="Ablation 8", claim="Mechanism ablation from always-on bands to V7f",
         keys=["abl.v6.by", "abl.v6.oc", "abl.v7f.by", "abl.v7f.oc", "abl.host.by", "abl.host.oc", "abl.v7d.kitoc", "abl.v7e.kitoc"],
         experiment="one change at a time", dataset="MOT17 val-half, KITTI", detector="YOLOX-X, YOLOv8n",
         tracker="ByteTrack, OC-SORT, BoostTrack", metric="HOTA", status="development, no intervals", wording="development values"),
    dict(id="A-3", section="Ablation 8", claim="Historical SCI adds neither accuracy nor compute saving on top of V7f",
         keys=["fw.c_a.int.dHOTA", "fw.b_a.int.dHOTA", "fw.d_c.int.dHOTA", "fw.d_c.off.dMOTA", "fw.d_p1.int.dHOTA"],
         experiment="pre-registered factorial", dataset="VisDrone val", detector="YOLOv8n, RT-DETR-L", tracker="ByteTrack",
         metric="HOTA, MOTA", status="development, pre-registered", wording="as stated"),
    dict(id="R-1", section="Runtime 9 / Abstract", claim="V7f costs 2.95 ms per frame on a 4-vCPU Xeon; end-to-end +2.59 ms",
         keys=["rt.v7f.ctrl", "rt.v7f.ctrl95", "rt.e2e_delta", "rt.e2e_pct", "rt.pipe_pct"], experiment="live YOLOv8n + ByteTrack",
         dataset="KITTI frames", detector="YOLOv8n", tracker="ByteTrack", metric="ms", status="CPU timing",
         wording="CPU only; no conversion to other hardware"),
    dict(id="R-2", section="Runtime 9", claim="General AC-MOT overhead on a 2-thread EPYC for three detectors",
         keys=["g1rt.yolov8.g1.score", "g1rt.rtdetr.g1.score", "g1rt.retinanet.g1.score", "g1rt.yolov8.pct", "g1rt.rtdetr.pct",
               "g1rt.retinanet.pct"], experiment="G1 runtime benchmark", dataset="VisDrone val frames",
         detector="YOLOv8n, RT-DETR-L, RetinaNet", tracker="ByteTrack", metric="ms, %", status="CPU timing", wording="diagnostic"),
    dict(id="B-1", section="Boundary 11", claim="C-TWiX KITTIMOTS car loss arises in a sparse sequence near the regime boundary",
         keys=["ctx.kcar.dHOTA", "ctx.kcar.seq0014"], files=[F + "recent/ctwix/audit_KITTIMOT.json", "figures/fig_data.json (fig8)"],
         experiment="audit of frozen layer decisions", dataset="KITTIMOTS val", detector="PermaTrack", tracker="C-TWiX",
         metric="HOTA, regime", status="post-freeze external", wording="regime decision without margin or hysteresis is fragile on sparse streams"),
    dict(id="B-2", section="Boundary 11", claim="OC-SORT official protocol: new catastrophic sequences", keys=["oc.cat.base.off", "oc.cat.g1.off"],
         experiment="G1 host tests", dataset="VisDrone val", detector="YOLOv8n, RT-DETR-L", tracker="OC-SORT", metric="catastrophic",
         status="development trackers", wording="trade-off; cause not isolated"),
    dict(id="B-3", section="Boundary 11", claim="Dynamic compute has little headroom on the tested aerial data",
         keys=["or.m3", "or.f736", "g2.s1_100", "g2.s2_35", "g2.gate", "g2.cost", "gsci.D.G", "gsci.B.G", "cue.none"],
         experiment="GT oracle, cue audit, supplementary G2 gates", dataset="VisDrone val", detector="YOLOv8n, RT-DETR-L",
         tracker="ByteTrack", metric="HOTA", status="development, supplementary (G2 not frozen)",
         wording="oracle gains below the pre-registered gate; GSCI is a difficulty measure, not a compute controller"),
    dict(id="P-1", section="Published comparison 10", claim="Reproductions within one HOTA point of the reported values (excluding failed TOPICTrack)",
         keys=["ref.st.HOTA", "mot.st.base.HOTA", "ref.bt.HOTA", "mot.bt.base.HOTA", "ref.oc.HOTA", "mot.oc.base.HOTA",
               "ref.hy.HOTA", "ext.hy.base.HOTA", "ctx.mot.refHOTA", "ctx.mot.base.HOTA", "ctx.kcar.refHOTA", "ctx.kcar.base.HOTA",
               "ctx.dance.refHOTA", "ctx.dance.base.HOTA", "tt.dance.refHOTA", "tt.dance.base.HOTA"],
         experiment="reproductions", dataset="validation splits", detector="published detections", tracker="published trackers",
         metric="HOTA", status="internal evaluation", wording="no state-of-the-art claim; not comparable with leaderboards"),
]
