"""
Lightning AI version of notebooks/YOLO11m_VisDrone_train_and_cache.ipynb.

Unlike Colab or Kaggle, a Lightning Studio has no fixed session wall and its
`/teamspace/studios/<name>` disk is already persistent local block storage, so
there is no Drive mount, no 12h session guard, and no "copy to fast local
disk" step. What differs from the Colab notebook: paths, a SMOKE/FULL mode
switch (env var AC_MOT_MODE, default SMOKE so a bare invocation never starts
the 40-epoch run by accident), a GPU/version assertion, and a flat .py script
(not a notebook) so it can run detached under tmux without a kernel server.
Every scientific cell (split, conversion, training arguments, manifest) is
taken verbatim from the Colab notebook, and this script asserts that.

  python notebooks/lightning/make_lightning_script.py

Writes notebooks/lightning/run_yolo11m_visdrone.py. Cache-grid generation
(CACHE_RES x NMS_IOU) is a separate, later stage (needs VisDrone-val transferred
and a verified last.pt first) and is intentionally not emitted by this script.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "YOLO11m_VisDrone_train_and_cache.ipynb"
OUT_PY = HERE / "run_yolo11m_visdrone.py"


def src(c):
    return c["source"] if isinstance(c["source"], str) else "".join(c["source"])


HEADER = '''"""
GENERATED by notebooks/lightning/make_lightning_script.py — do not hand-edit.
Lightning-adapted, flat-script version of notebooks/YOLO11m_VisDrone_train_and_cache.ipynb.
Run detached: tmux new -s yolo11m_train 'python3 notebooks/lightning/run_yolo11m_visdrone.py 2>&1 | tee -a $LOG'

Mode is controlled by the AC_MOT_MODE env var: SMOKE (default) or FULL.
SMOKE never trains the real 40-epoch run; it only exercises the real CUDA
forward/backward path, at the real IMGSZ/BATCH, on a tiny data fraction, and
validates true-resume (stop after epoch 1, restore the full optimizer
checkpoint, resume, verify 2 epochs landed in results.csv) without touching
the FULL run's output directory.
"""
import glob
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time

import numpy as np
import torch
import ultralytics
from PIL import Image

MODE = os.environ.get("AC_MOT_MODE", "SMOKE").strip().upper()
assert MODE in ("SMOKE", "FULL"), f"AC_MOT_MODE must be SMOKE or FULL, got {MODE!r}"
SMOKE = MODE == "SMOKE"
RUN_T0 = time.time()

BASE = "/teamspace/studios/this_studio"
'''

ENV_BLOCK = '''
# ---- environment / version record (hard gate: no CPU fallback) -----------------------------
def _nvidia_smi():
    try:
        out = subprocess.run(
            ["nvidia-smi", "--query-gpu=name,driver_version,memory.total", "--format=csv,noheader"],
            capture_output=True, text=True, timeout=10, check=True,
        ).stdout.strip()
        name, driver, vram = [x.strip() for x in out.split(",")]
        return dict(name=name, driver_version=driver, memory_total=vram)
    except Exception as e:
        return dict(error=str(e))


def _git_info():
    try:
        sha = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=BASE_REPO).stdout.strip()
        dirty = bool(subprocess.run(["git", "status", "--short"], capture_output=True, text=True, cwd=BASE_REPO).stdout.strip())
        return dict(commit=sha or None, dirty=dirty)
    except Exception as e:
        return dict(error=str(e))


BASE_REPO = os.environ.get("AC_MOT_REPO", BASE)
assert torch.cuda.is_available(), "No CUDA GPU visible: this run must not continue on CPU."
ENV = dict(
    mode=MODE,
    python=sys.version.split()[0],
    torch=torch.__version__,
    torch_cuda_build=torch.version.cuda,
    cudnn=torch.backends.cudnn.version(),
    cuda_available=torch.cuda.is_available(),
    gpu_name=torch.cuda.get_device_name(0),
    gpu_vram_bytes=torch.cuda.get_device_properties(0).total_memory,
    ultralytics=ultralytics.__version__,
    nvidia_smi=_nvidia_smi(),
    git=_git_info(),
    started_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
)
print(json.dumps(ENV, indent=1))
'''

PATHS_BLOCK = '''
# ---- paths (Lightning persistent storage; /teamspace/studios/<name> survives stop/start) ----
TRAIN = f"{BASE}/data/VisDrone2019-MOT-train"
TRAIN_ZIP = ""
VAL = ""          # filled in for the later caching stage
VAL_ZIP = ""
UAVDT = ""        # filled in for the later caching stage
OUT = f"{BASE}/outputs/acmot_oatrack"
'''

TRAIN_CALL_ARGS = (
    "imgsz=IMGSZ, epochs=EPOCHS, batch=BATCH, seed=SEED, deterministic=True,\n"
    "                project=f'{OUT}/train', name='yolo11m_vd1536', exist_ok=True, workers=2, save_period=1,\n"
    "                close_mosaic=10, plots=True"
)

SMOKE_BLOCK = '''
# ---- SMOKE: real CUDA path at the real IMGSZ/BATCH on a tiny fraction, plus true-resume check ----
if SMOKE:
    assert len(TRAIN_SEQS) == 56, len(TRAIN_SEQS)
    assert abs(n_frames - 24201) / 24201 < 0.02, n_frames
    assert IMGSZ == 1536 and BATCH == 4 and FRAME_STRIDE == 1 and EPOCHS == 40, (IMGSZ, BATCH, FRAME_STRIDE, EPOCHS)
    os.makedirs(OUT, exist_ok=True)
    probe = f"{OUT}/_write_test"
    open(probe, "w").write("ok")
    os.remove(probe)

    from ultralytics import YOLO

    sd = f"{OUT}/smoke/run"
    full_s = f"{sd}/weights/resume_full.pt"

    def keep_full_s(tr):
        shutil.copy2(tr.last, f"{tr.save_dir}/weights/resume_full.pt")

    def stop_after_first(tr):
        if tr.epoch == 0 and not os.path.exists(f"{tr.save_dir}/_resumed"):
            tr.stop = True

    torch.cuda.reset_peak_memory_stats()
    smoke_t0 = time.time()
    m = YOLO("yolo11m.pt")
    m.add_callback("on_model_save", keep_full_s)
    m.add_callback("on_fit_epoch_end", stop_after_first)
    m.train(data=f"{Y}/data.yaml", imgsz=IMGSZ, epochs=2, batch=BATCH, seed=SEED, deterministic=True,
            fraction=0.004, project=f"{OUT}/smoke", name="run", exist_ok=True, workers=2,
            close_mosaic=0, plots=False)
    peak_alloc = torch.cuda.max_memory_allocated()
    peak_reserved = torch.cuda.max_memory_reserved()
    print("peak GPU allocated (GB)", round(peak_alloc / 2**30, 3))
    print("peak GPU reserved  (GB)", round(peak_reserved / 2**30, 3))

    shutil.copy2(full_s, f"{sd}/weights/last.pt")
    open(f"{sd}/_resumed", "w").write("1")
    m2 = YOLO(f"{sd}/weights/last.pt")
    m2.add_callback("on_model_save", keep_full_s)
    m2.train(resume=True)
    rows = open(f"{sd}/results.csv").read().strip().splitlines()[1:]
    assert len(rows) == 2, rows
    print("true-resume check passed: 2 epochs present in results.csv after stop+resume")

    report = dict(
        env=ENV,
        gate=dict(imgsz=IMGSZ, batch=BATCH, frame_stride=FRAME_STRIDE, epochs_protocol=EPOCHS,
                   dataset_sequences=len(TRAIN_SEQS), dataset_frames=n_frames,
                   class_set=CLASS_SET, class_map=CLS, names=NAMES),
        cuda=dict(peak_allocated_bytes=peak_alloc, peak_reserved_bytes=peak_reserved,
                   no_cpu_fallback=True),
        resume_check=dict(epochs_after_resume=len(rows), passed=True),
        output_dir=OUT,
        smoke_run_dir=sd,
        persistent_storage_path=BASE,
        wall_seconds=time.time() - smoke_t0,
        command=f"AC_MOT_MODE=SMOKE python3 {os.path.abspath(__file__)}",
    )
    report_path = f"{OUT}/SMOKE_REPORT.json"
    json.dump(report, open(report_path, "w"), indent=1)
    print("SMOKE CHECKS PASSED —", report_path)
'''

TRAIN_BLOCK = '''
# ---- FULL: 40-epoch run, true resume from the last legitimate checkpoint on restart ----
if not SMOKE:
    from ultralytics import YOLO

    run_dir = f"{OUT}/train/yolo11m_vd1536"
    last = f"{run_dir}/weights/last.pt"
    full = f"{run_dir}/weights/resume_full.pt"   # full checkpoint (optimizer/scheduler kept) after every epoch
    DONE = f"{OUT}/TRAINING_DONE"

    def keep_full(trainer):
        shutil.copy2(trainer.last, full)

    def log_epoch_timing(trainer):
        f = f"{OUT}/EPOCH_TIMING.jsonl"
        elapsed = time.time() - trainer.train_time_start
        done = trainer.epoch + 1 - trainer.start_epoch
        per_epoch = elapsed / max(done, 1)
        rec = dict(epoch=trainer.epoch + 1, epochs_total=trainer.epochs, elapsed_s=elapsed,
                   mean_s_per_epoch=per_epoch,
                   projected_remaining_s=per_epoch * (trainer.epochs - trainer.epoch - 1),
                   projected_total_gpu_hours=per_epoch * trainer.epochs / 3600.0,
                   utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
        with open(f, "a") as fh:
            fh.write(json.dumps(rec) + "\\n")
        print("epoch", rec["epoch"], "of", rec["epochs_total"], "took", round(elapsed if rec["epoch"] == 1 else per_epoch, 1),
              "s (mean/epoch); projected total", round(rec["projected_total_gpu_hours"], 2), "GPU-h")

    def epochs_done():
        f = f"{run_dir}/results.csv"
        return len(open(f).read().strip().splitlines()) - 1 if os.path.exists(f) else 0

    if not os.path.exists(DONE):
        if os.path.exists(full):
            shutil.copy2(full, last)   # an earlier interruption may have stripped the optimizer from last.pt
            start_epoch = epochs_done()
            print("resuming true training state from", full, "— epochs already completed:", start_epoch)
            model = YOLO(last)
            model.add_callback("on_model_save", keep_full)
            model.add_callback("on_fit_epoch_end", log_epoch_timing)
            model.train(resume=True)
        else:
            print("starting FULL training from yolo11m.pt —", EPOCHS, "epochs,", "imgsz", IMGSZ, "batch", BATCH)
            model = YOLO("yolo11m.pt")
            model.add_callback("on_model_save", keep_full)
            model.add_callback("on_fit_epoch_end", log_epoch_timing)
            model.train(data=f"{Y}/data.yaml", TRAIN_CALL_ARGS_PLACEHOLDER)
        n_done = epochs_done()
        print("epochs completed:", n_done, "of", EPOCHS)
        if n_done == EPOCHS:
            open(DONE, "w").write(json.dumps(dict(epochs=EPOCHS, env=ENV,
                                                    finished_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))))
    TRAINING_DONE = os.path.exists(DONE)
    print("TRAINING_DONE", TRAINING_DONE)
'''.replace("TRAIN_CALL_ARGS_PLACEHOLDER", TRAIN_CALL_ARGS)

MANIFEST_BLOCK = '''
# ---- manifest: last epoch's checkpoint, never selected on any held-out split ----
if not SMOKE and TRAINING_DONE:
    W8 = f"{OUT}/train/yolo11m_vd1536/weights/last.pt"   # last epoch, not 'best' (no selection on any split)
    sha = hashlib.sha256(open(W8, "rb").read()).hexdigest()
    json.dump(dict(weights=W8, sha256=sha, model="yolo11m.pt", imgsz=IMGSZ, epochs=EPOCHS, batch=BATCH,
                   frame_stride=FRAME_STRIDE, seed=SEED, class_set=CLASS_SET, class_map=CLS, names=NAMES,
                   train_sequences=TRAIN_SEQS, train_frames=n_frames, calibration=CALIBRATION, env=ENV,
                   status="paper-aligned re-implementation (epochs, augmentation, class mapping and the smallobj "
                          "configuration of OATrack are not published)"),
              open(f"{OUT}/DETECTOR_MANIFEST.json", "w"), indent=1)
    print("manifest sha256", sha)
'''


def build():
    nb = json.loads(SRC.read_text())
    cells = nb["cells"]
    s = [src(c) for c in cells]
    # environment cells being replaced — asserted, so a change in the Colab notebook is noticed
    assert s[1].startswith("!nvidia-smi") and "google.colab" in s[2]
    assert s[7].startswith("CALIBRATION = ") and "DETECTOR_TRAIN" in s[7] and "EXCLUDED_PROTECTED" in s[7]
    assert s[9].startswith("import os, zipfile") and "/content/data" in s[9]
    assert s[11].startswith("import numpy as np") and "/content/yolo" in s[11]
    assert s[13].startswith("from ultralytics import YOLO") and "model.train(data=" in s[13]
    assert s[14].startswith("import hashlib, json") and "status='paper-aligned" in s[14]
    for key in TRAIN_CALL_ARGS.split(",\n"):
        assert key.strip() in s[13], key

    params = s[4].split("OUT = ")[1].split("\n", 1)[1]   # IMGSZ ... NMS_IOU, verbatim from the Colab cell

    split_block = s[7]   # CALIBRATION / DETECTOR_TRAIN / EXCLUDED_PROTECTED — verbatim, scientific
    convert_block = (
        s[11]
        .replace("/content/yolo", "'{BASE}/yolo'".replace("{BASE}", "' + BASE + '"))
    )
    # the replace above is fragile for an f-string-free source; do it as a literal substitution instead
    convert_block = s[11].replace("Y = '/content/yolo'", "Y = f'{BASE}/yolo'")
    assert convert_block != s[11] or "/content/yolo" not in s[11]

    local_block = s[9].replace(
        "    else:\n        shutil.copytree(path, dst)\n    return dst",
        "    else:\n        return path  # already on persistent, fast local disk: no duplicate copy\n    return dst",
    )
    assert "return path" in local_block

    parts = [
        HEADER,
        ENV_BLOCK,
        PATHS_BLOCK,
        params,
        "\n# ---- split (fixed before training; identical to the Colab/Kaggle notebooks) ----\n" + split_block,
        "\n# ---- data to local disk (no-op copy: Lightning persistent storage is already local) ----\n" + local_block,
        "\n# ---- convert to YOLO format (verbatim scientific logic; only the output root changed) ----\n" + convert_block,
        SMOKE_BLOCK,
        TRAIN_BLOCK,
        MANIFEST_BLOCK,
    ]
    OUT_PY.write_text("\n".join(p.strip("\n") for p in parts) + "\n")
    print("wrote", OUT_PY)


if __name__ == "__main__":
    build()
