"""
GENERATED by notebooks/lightning/make_lightning_script.py — do not hand-edit.
Lightning-adapted, flat-script version of notebooks/YOLO11m_VisDrone_train_and_cache.ipynb.
Run detached: tmux new -s yolo11m_train 'python3 notebooks/lightning/run_yolo11m_visdrone.py 2>&1 | tee -a $LOG'

Mode is controlled by the AC_MOT_MODE env var: SMOKE (default) or FULL.
SMOKE never trains the real 40-epoch run; it only exercises the real CUDA
forward/backward path, at the real IMGSZ/BATCH, on a tiny data fraction, and
validates true-resume (stop after epoch 1, restore the full optimizer
checkpoint, resume, verify 2 epochs landed in results.csv) without touching
the FULL run's output directory.
"""
import glob
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time

import numpy as np
import torch
import ultralytics
from PIL import Image

MODE = os.environ.get("AC_MOT_MODE", "SMOKE").strip().upper()
assert MODE in ("SMOKE", "FULL"), f"AC_MOT_MODE must be SMOKE or FULL, got {MODE!r}"
SMOKE = MODE == "SMOKE"
RUN_T0 = time.time()

BASE = "/teamspace/studios/this_studio"
# ---- environment / version record (hard gate: no CPU fallback) -----------------------------
def _nvidia_smi():
    try:
        out = subprocess.run(
            ["nvidia-smi", "--query-gpu=name,driver_version,memory.total", "--format=csv,noheader"],
            capture_output=True, text=True, timeout=10, check=True,
        ).stdout.strip()
        name, driver, vram = [x.strip() for x in out.split(",")]
        return dict(name=name, driver_version=driver, memory_total=vram)
    except Exception as e:
        return dict(error=str(e))


def _git_info():
    try:
        sha = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=BASE_REPO).stdout.strip()
        dirty = bool(subprocess.run(["git", "status", "--short"], capture_output=True, text=True, cwd=BASE_REPO).stdout.strip())
        return dict(commit=sha or None, dirty=dirty)
    except Exception as e:
        return dict(error=str(e))


BASE_REPO = os.environ.get("AC_MOT_REPO", BASE)
assert torch.cuda.is_available(), "No CUDA GPU visible: this run must not continue on CPU."
ENV = dict(
    mode=MODE,
    python=sys.version.split()[0],
    torch=torch.__version__,
    torch_cuda_build=torch.version.cuda,
    cudnn=torch.backends.cudnn.version(),
    cuda_available=torch.cuda.is_available(),
    gpu_name=torch.cuda.get_device_name(0),
    gpu_vram_bytes=torch.cuda.get_device_properties(0).total_memory,
    ultralytics=ultralytics.__version__,
    nvidia_smi=_nvidia_smi(),
    git=_git_info(),
    started_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
)
print(json.dumps(ENV, indent=1))
# ---- paths (Lightning persistent storage; /teamspace/studios/<name> survives stop/start) ----
TRAIN = f"{BASE}/data/VisDrone2019-MOT-train"
TRAIN_ZIP = ""
VAL = ""          # filled in for the later caching stage
VAL_ZIP = ""
UAVDT = ""        # filled in for the later caching stage
OUT = f"{BASE}/outputs/acmot_oatrack"
IMGSZ = 1536
EPOCHS = 40          # not stated by the paper (choice recorded in the manifest)
BATCH = 4            # T4 16 GB at 1536 px
FRAME_STRIDE = 1     # every frame (paper: the converted training split)
SEED = 0
CLASS_SET = 'eval5'  # 'eval5': pedestrian, car, van, truck, bus | 'all10': the ten VisDrone categories
CACHE_RES = [1088, 1280, 1536]   # detector input sizes AC-MOT may choose
NMS_IOU = [0.45, 0.60, 0.70]     # NMS operating points (0.70 = Ultralytics default)
# ---- split (fixed before training; identical to the Colab/Kaggle notebooks) ----
CALIBRATION = ["uav0000316_01288_v", "uav0000289_06922_v", "uav0000013_00000_v", "uav0000076_00720_v", "uav0000307_00000_v", "uav0000020_00406_v", "uav0000315_00000_v", "uav0000243_00001_v"]
DETECTOR_TRAIN = ["uav0000013_01392_v", "uav0000071_03240_v", "uav0000072_04488_v", "uav0000079_00480_v", "uav0000084_00000_v", "uav0000126_00001_v", "uav0000138_00000_v", "uav0000143_02250_v", "uav0000218_00001_v", "uav0000222_03150_v", "uav0000239_03720_v", "uav0000239_12336_v", "uav0000263_03289_v", "uav0000264_02760_v", "uav0000270_00001_v", "uav0000278_00001_v", "uav0000279_00001_v", "uav0000288_00001_v", "uav0000289_00001_v", "uav0000295_02300_v", "uav0000300_00000_v", "uav0000308_01380_v", "uav0000309_00000_v", "uav0000326_01035_v", "uav0000329_04715_v", "uav0000342_04692_v", "uav0000352_05980_v", "uav0000357_00920_v", "uav0000360_00001_v", "uav0000361_02323_v", "uav0000363_00001_v", "uav0000366_00001_v"]
EXCLUDED_PROTECTED = ["uav0000013_01073_v", "uav0000072_05448_v", "uav0000072_06432_v", "uav0000099_02109_v", "uav0000124_00944_v", "uav0000140_01590_v", "uav0000145_00000_v", "uav0000150_02310_v", "uav0000244_01440_v", "uav0000248_00001_v", "uav0000266_03598_v", "uav0000266_04830_v", "uav0000273_00001_v", "uav0000281_00460_v", "uav0000308_00000_v", "uav0000323_01173_v"]
assert not set(CALIBRATION) & set(EXCLUDED_PROTECTED)
print(len(CALIBRATION), 'calibration sequences')
# ---- data to local disk (no-op copy: Lightning persistent storage is already local) ----
import os, zipfile, shutil, glob
def local(path, zpath, name):
    dst = f'/content/data/{name}'
    if os.path.isdir(f'{dst}/sequences'):
        return dst
    os.makedirs('/content/data', exist_ok=True)
    if zpath:
        with zipfile.ZipFile(zpath) as z:
            z.extractall('/content/data/_x')
        src = glob.glob('/content/data/_x/**/sequences', recursive=True)[0][:-len('/sequences')]
        shutil.move(src, dst)
        shutil.rmtree('/content/data/_x', ignore_errors=True)
    else:
        return path  # already on persistent, fast local disk: no duplicate copy
    return dst
TR = local(TRAIN, TRAIN_ZIP, 'train')
seqs = sorted(os.listdir(f'{TR}/sequences'))
assert len(seqs) == 56, len(seqs)
missing = [s for s in CALIBRATION if s not in seqs]
assert not missing, missing
n_frames = sum(len(glob.glob(f'{TR}/sequences/{s}/*.jpg')) for s in seqs)
print(len(seqs), 'train sequences,', n_frames, 'frames (paper: 56 / 24,201)')
TRAIN_SEQS = seqs
# ---- convert to YOLO format (verbatim scientific logic; only the output root changed) ----
import numpy as np
from PIL import Image
if CLASS_SET == 'eval5':
    CLS = {1: 0, 4: 1, 5: 2, 6: 3, 9: 4}
    NAMES = ['pedestrian', 'car', 'van', 'truck', 'bus']
else:
    CLS = {k: k - 1 for k in range(1, 11)}
    NAMES = ['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck', 'tricycle', 'awning-tricycle', 'bus', 'motor']
Y = f'{BASE}/yolo'
def convert(seq_list, part, stride):
    n = 0
    for s in seq_list:
        a = np.loadtxt(f'{TR}/annotations/{s}.txt', delimiter=',', ndmin=2)
        frames = sorted(glob.glob(f'{TR}/sequences/{s}/*.jpg'))
        W, H = Image.open(frames[0]).size
        for k, f in enumerate(frames):
            if k % stride:
                continue
            t = k + 1
            img = f'{Y}/images/{part}/{s}_{t:07d}.jpg'
            if not os.path.exists(img):
                os.makedirs(os.path.dirname(img), exist_ok=True)
                os.symlink(f, img)
            rows = a[(a[:, 0] == t) & (a[:, 6] == 1) & np.isin(a[:, 7], list(CLS))]
            os.makedirs(f'{Y}/labels/{part}', exist_ok=True)
            with open(f'{Y}/labels/{part}/{s}_{t:07d}.txt', 'w') as fh:
                for r in rows:
                    x, y, w, h = r[2:6]
                    x, y = max(x, 0), max(y, 0)
                    w, h = min(w, W - x), min(h, H - y)
                    if w > 1 and h > 1:
                        fh.write(f'{CLS[int(r[7])]} {(x + w / 2) / W:.6f} {(y + h / 2) / H:.6f} {w / W:.6f} {h / H:.6f}\n')
            n += 1
    return n
print('train images', convert(TRAIN_SEQS, 'train', FRAME_STRIDE))
print('monitor images', convert(CALIBRATION, 'val', 10))   # inside the training set: progress monitor only
open(f'{Y}/data.yaml', 'w').write(f'path: {Y}\ntrain: images/train\nval: images/val\nnames: {NAMES}\n')
# ---- SMOKE: real CUDA path at the real IMGSZ/BATCH on a tiny fraction, plus true-resume check ----
if SMOKE:
    assert len(TRAIN_SEQS) == 56, len(TRAIN_SEQS)
    assert abs(n_frames - 24201) / 24201 < 0.02, n_frames
    assert IMGSZ == 1536 and BATCH == 4 and FRAME_STRIDE == 1 and EPOCHS == 40, (IMGSZ, BATCH, FRAME_STRIDE, EPOCHS)
    os.makedirs(OUT, exist_ok=True)
    probe = f"{OUT}/_write_test"
    open(probe, "w").write("ok")
    os.remove(probe)

    from ultralytics import YOLO

    sd = f"{OUT}/smoke/run"
    full_s = f"{sd}/weights/resume_full.pt"

    def keep_full_s(tr):
        shutil.copy2(tr.last, f"{tr.save_dir}/weights/resume_full.pt")

    def stop_after_first(tr):
        if tr.epoch == 0 and not os.path.exists(f"{tr.save_dir}/_resumed"):
            tr.stop = True

    torch.cuda.reset_peak_memory_stats()
    smoke_t0 = time.time()
    m = YOLO("yolo11m.pt")
    m.add_callback("on_model_save", keep_full_s)
    m.add_callback("on_fit_epoch_end", stop_after_first)
    m.train(data=f"{Y}/data.yaml", imgsz=IMGSZ, epochs=2, batch=BATCH, seed=SEED, deterministic=True,
            fraction=0.004, project=f"{OUT}/smoke", name="run", exist_ok=True, workers=2,
            close_mosaic=0, plots=False)
    peak_alloc = torch.cuda.max_memory_allocated()
    peak_reserved = torch.cuda.max_memory_reserved()
    print("peak GPU allocated (GB)", round(peak_alloc / 2**30, 3))
    print("peak GPU reserved  (GB)", round(peak_reserved / 2**30, 3))

    shutil.copy2(full_s, f"{sd}/weights/last.pt")
    open(f"{sd}/_resumed", "w").write("1")
    m2 = YOLO(f"{sd}/weights/last.pt")
    m2.add_callback("on_model_save", keep_full_s)
    m2.train(resume=True)
    rows = open(f"{sd}/results.csv").read().strip().splitlines()[1:]
    assert len(rows) == 2, rows
    print("true-resume check passed: 2 epochs present in results.csv after stop+resume")

    report = dict(
        env=ENV,
        gate=dict(imgsz=IMGSZ, batch=BATCH, frame_stride=FRAME_STRIDE, epochs_protocol=EPOCHS,
                   dataset_sequences=len(TRAIN_SEQS), dataset_frames=n_frames,
                   class_set=CLASS_SET, class_map=CLS, names=NAMES),
        cuda=dict(peak_allocated_bytes=peak_alloc, peak_reserved_bytes=peak_reserved,
                   no_cpu_fallback=True),
        resume_check=dict(epochs_after_resume=len(rows), passed=True),
        output_dir=OUT,
        smoke_run_dir=sd,
        persistent_storage_path=BASE,
        wall_seconds=time.time() - smoke_t0,
        command=f"AC_MOT_MODE=SMOKE python3 {os.path.abspath(__file__)}",
    )
    report_path = f"{OUT}/SMOKE_REPORT.json"
    json.dump(report, open(report_path, "w"), indent=1)
    print("SMOKE CHECKS PASSED —", report_path)
# ---- FULL: 40-epoch run, true resume from the last legitimate checkpoint on restart ----
if not SMOKE:
    from ultralytics import YOLO

    run_dir = f"{OUT}/train/yolo11m_vd1536"
    last = f"{run_dir}/weights/last.pt"
    full = f"{run_dir}/weights/resume_full.pt"   # full checkpoint (optimizer/scheduler kept) after every epoch
    DONE = f"{OUT}/TRAINING_DONE"

    def keep_full(trainer):
        shutil.copy2(trainer.last, full)

    def log_epoch_timing(trainer):
        f = f"{OUT}/EPOCH_TIMING.jsonl"
        elapsed = time.time() - trainer.train_time_start
        done = trainer.epoch + 1 - trainer.start_epoch
        per_epoch = elapsed / max(done, 1)
        rec = dict(epoch=trainer.epoch + 1, epochs_total=trainer.epochs, elapsed_s=elapsed,
                   mean_s_per_epoch=per_epoch,
                   projected_remaining_s=per_epoch * (trainer.epochs - trainer.epoch - 1),
                   projected_total_gpu_hours=per_epoch * trainer.epochs / 3600.0,
                   utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
        with open(f, "a") as fh:
            fh.write(json.dumps(rec) + "\n")
        print("epoch", rec["epoch"], "of", rec["epochs_total"], "took", round(elapsed if rec["epoch"] == 1 else per_epoch, 1),
              "s (mean/epoch); projected total", round(rec["projected_total_gpu_hours"], 2), "GPU-h")

    def epochs_done():
        f = f"{run_dir}/results.csv"
        return len(open(f).read().strip().splitlines()) - 1 if os.path.exists(f) else 0

    if not os.path.exists(DONE):
        if os.path.exists(full):
            shutil.copy2(full, last)   # an earlier interruption may have stripped the optimizer from last.pt
            start_epoch = epochs_done()
            print("resuming true training state from", full, "— epochs already completed:", start_epoch)
            model = YOLO(last)
            model.add_callback("on_model_save", keep_full)
            model.add_callback("on_fit_epoch_end", log_epoch_timing)
            model.train(resume=True)
        else:
            print("starting FULL training from yolo11m.pt —", EPOCHS, "epochs,", "imgsz", IMGSZ, "batch", BATCH)
            model = YOLO("yolo11m.pt")
            model.add_callback("on_model_save", keep_full)
            model.add_callback("on_fit_epoch_end", log_epoch_timing)
            model.train(data=f"{Y}/data.yaml", imgsz=IMGSZ, epochs=EPOCHS, batch=BATCH, seed=SEED, deterministic=True,
                project=f'{OUT}/train', name='yolo11m_vd1536', exist_ok=True, workers=2, save_period=1,
                close_mosaic=10, plots=True)
        n_done = epochs_done()
        print("epochs completed:", n_done, "of", EPOCHS)
        if n_done == EPOCHS:
            open(DONE, "w").write(json.dumps(dict(epochs=EPOCHS, env=ENV,
                                                    finished_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))))
    TRAINING_DONE = os.path.exists(DONE)
    print("TRAINING_DONE", TRAINING_DONE)
# ---- manifest: last epoch's checkpoint, never selected on any held-out split ----
if not SMOKE and TRAINING_DONE:
    W8 = f"{OUT}/train/yolo11m_vd1536/weights/last.pt"   # last epoch, not 'best' (no selection on any split)
    sha = hashlib.sha256(open(W8, "rb").read()).hexdigest()
    json.dump(dict(weights=W8, sha256=sha, model="yolo11m.pt", imgsz=IMGSZ, epochs=EPOCHS, batch=BATCH,
                   frame_stride=FRAME_STRIDE, seed=SEED, class_set=CLASS_SET, class_map=CLS, names=NAMES,
                   train_sequences=TRAIN_SEQS, train_frames=n_frames, calibration=CALIBRATION, env=ENV,
                   status="paper-aligned re-implementation (epochs, augmentation, class mapping and the smallobj "
                          "configuration of OATrack are not published)"),
              open(f"{OUT}/DETECTOR_MANIFEST.json", "w"), indent=1)
    print("manifest sha256", sha)
