"""
GENERATED by notebooks/lightning/make_cache_script.py -- do not hand-edit.
Detector cache generation for the frozen public YOLO11m-VisDrone checkpoint.
Run detached: tmux new -s cache_gen 'python3 notebooks/lightning/run_cache_generation.py 2>&1 | tee -a $LOG'
"""
import glob
import json
import os
import time

import cv2
import numpy as np
import torch
from ultralytics import YOLO

BASE = "/teamspace/studios/this_studio"
TR = f"{BASE}/data/VisDrone2019-MOT-train"
VA = f"{BASE}/data/VisDrone2019-MOT-val"
OUT = f"{BASE}/outputs/acmot_oatrack"
FROZEN_CKPT = f"{BASE}/detector/frozen/yolo11m_visdrone_frozen.pt"
FROZEN_SHA256 = "c6f98247e7c731a567aaf37ca7b808beff588b687623e028b25a2e1d846e96e7"

CACHE_RES = [1088, 1280, 1536]
NMS_IOU = [0.45, 0.60, 0.70]

# split roles kept explicit and separate (train/calibration/final-evaluation never mixed):
CALIBRATION = ["uav0000316_01288_v", "uav0000289_06922_v", "uav0000013_00000_v", "uav0000076_00720_v",
               "uav0000307_00000_v", "uav0000020_00406_v", "uav0000315_00000_v", "uav0000243_00001_v"]

# post-detection eval5 filter/remap (checkpoint class index -> eval5 index); no retraining, no threshold tuning.
# documented in research/acmot_paper_v2/frozen_detector/DETECTOR_PROVENANCE.json -> class_mapping_for_acmot_eval5_protocol
CKPT_TO_EVAL5 = {0: 0, 3: 1, 4: 2, 5: 3, 8: 4}
EVAL5_NAMES = ["pedestrian", "car", "van", "truck", "bus"]


def _sha256(path):
    import hashlib
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


actual_sha = _sha256(FROZEN_CKPT)
assert actual_sha == FROZEN_SHA256, f"frozen checkpoint sha256 mismatch: {actual_sha} != {FROZEN_SHA256}"

det_model = YOLO(FROZEN_CKPT)
HALF = torch.cuda.is_available()
assert torch.cuda.is_available(), "No CUDA GPU visible: cache generation must not run on CPU."


def _clone(x):
    if isinstance(x, torch.Tensor):
        return x.clone()
    if isinstance(x, (list, tuple)):
        return type(x)(_clone(v) for v in x)
    return x


def multi_nms_predict(model, path, imgsz, nms_list):
    # one forward pass; the predictor's own postprocess per NMS value (== predict(iou=tau), tested) -- verbatim design
    model.predict(path, imgsz=imgsz, conf=0.01, iou=nms_list[0], max_det=1000, half=HALF, verbose=False)
    p = model.predictor
    im0 = cv2.imread(path)
    with torch.inference_mode():
        im = p.preprocess([im0])
        raw = p.inference(im)
        out = {}
        for tau in nms_list:
            p.args.iou = tau
            b = p.postprocess(_clone(raw), im, [im0])[0].boxes
            out[tau] = torch.cat([b.xyxy, b.conf[:, None], b.cls[:, None]], 1).cpu().numpy()
    return out, im0.shape[:2]


STATS = dict(forward_passes=0, frames_by_split={}, started_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))


def cache(root, seq_list, tag):
    STATS["frames_by_split"].setdefault(tag, 0)
    for res in CACHE_RES:
        dirs = {t: f"{OUT}/cache/yolo11m_vd/{tag}/r{res}_n{int(round(100 * t))}" for t in NMS_IOU}
        for d in dirs.values():
            os.makedirs(d, exist_ok=True)
        for s in seq_list:
            if all(os.path.exists(f"{d}/{s}.npz") for d in dirs.values()):
                print("skip (already cached)", tag, res, s)
                continue
            frames = sorted(glob.glob(f"{root}/sequences/{s}/*.jpg"))
            rows = {t: [] for t in NMS_IOU}
            times = []
            for t_, f in enumerate(frames, 1):
                t0 = time.perf_counter()
                out, shape = multi_nms_predict(det_model, f, res, NMS_IOU)
                torch.cuda.synchronize()
                times.append(time.perf_counter() - t0)
                STATS["forward_passes"] += 1
                for tau, a in out.items():
                    for r in a:
                        ck_cls = int(r[5])
                        if ck_cls not in CKPT_TO_EVAL5:
                            continue   # eval5 filter: drop checkpoint classes outside {pedestrian,car,van,truck,bus}
                        rows[tau].append([t_, *r[:4].tolist(), float(r[4]), CKPT_TO_EVAL5[ck_cls]])
            if res == CACHE_RES[0]:
                STATS["frames_by_split"][tag] += len(frames)
            for tau, d in dirs.items():
                np.savez_compressed(f"{d}/{s}.npz", det=np.asarray(rows[tau], np.float64).reshape(-1, 7),
                                    shape=np.asarray(shape), frames=len(frames))
            json.dump(dict(mean_ms_all_nms=1000 * float(np.mean(times[10:] or times)), frames=len(frames),
                           gpu=torch.cuda.get_device_name(0)),
                      open(f"{dirs[NMS_IOU[-1]]}/{s}.timing.json", "w"))
            print(tag, res, s, {t: len(v) for t, v in rows.items()}, "frames", len(frames))


t_cache_start = time.time()
cache(VA, sorted(os.listdir(f"{VA}/sequences")), "visdrone_val")
cache(TR, CALIBRATION, "visdrone_calib")
STATS["wall_seconds"] = time.time() - t_cache_start
STATS["finished_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
STATS["cache_res"] = CACHE_RES
STATS["nms_iou"] = NMS_IOU
STATS["frozen_checkpoint_sha256"] = FROZEN_SHA256
STATS["eval5_names"] = EVAL5_NAMES
STATS["class_filter"] = CKPT_TO_EVAL5
json.dump(STATS, open(f"{OUT}/CACHE_GENERATION_STATS.json", "w"), indent=1)
print(json.dumps(STATS, indent=1))
print("CACHE GENERATION DONE")
