"""
Refresh FACTUAL metadata in research/context (stdlib only):
  * the AUTO block at the top of PROJECT_STATE.md
  * GIT_STATE.md (fully generated)
It reads git, tags, lock statuses and the existence of result files listed in
RESULTS_CANONICAL.md. It never rewrites scientific conclusions.

  python3 tools/update_project_context.py
"""
from __future__ import annotations

import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CTX = ROOT / "research" / "context"
BEGIN = "<!-- AUTO:BEGIN (tools/update_project_context.py — do not edit by hand) -->"
END = "<!-- AUTO:END -->"


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                          text=True, check=True).stdout.strip()


def git_facts() -> dict:
    head = git("rev-parse", "HEAD")
    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    try:
        upstream = git("rev-parse", "--abbrev-ref", "@{u}")
        ahead, behind = git("rev-list", "--left-right", "--count",
                            f"HEAD...{upstream}").split()
    except subprocess.CalledProcessError:
        upstream, ahead, behind = "none", "?", "?"
    tags = []
    for t in git("tag", "--sort=creatordate").splitlines():
        tags.append((t, git("rev-list", "-n1", t),
                     git("log", "-1", "--format=%cs", t)))
    status = git("status", "--porcelain").splitlines()
    log = git("log", "--format=%h %cs %s", "-15").splitlines()
    return dict(head=head, branch=branch, upstream=upstream, ahead=ahead,
                behind=behind, tags=tags, status=status, log=log,
                remote=git("remote", "get-url", "origin"))


def lock_statuses() -> list[tuple[str, str]]:
    out = []
    for p in sorted((ROOT / "research").glob("*.json")):
        try:
            d = json.loads(p.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        out.append((p.name, str(d.get("status", "n/a (split/metadata)"))))
    return out


def result_files() -> list[tuple[str, bool]]:
    text = (CTX / "RESULTS_CANONICAL.md").read_text()
    paths = sorted(set(re.findall(r"`(outputs/[^`*]+?)`", text)))
    return [(p, (ROOT / p).exists()) for p in paths]


def main() -> None:
    g = git_facts()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    frozen = [t for t in g["tags"] if re.fullmatch(r"universal-acmot-v\w+-freeze", t[0])]
    latest = frozen[-1] if frozen else ("none", "", "")
    tree = ("clean" if not g["status"] else
            f"{len(g['status'])} uncommitted path(s) — see GIT_STATE.md")
    block = "\n".join([
        BEGIN,
        f"LAST VERIFIED COMMIT: {g['head']}",
        f"CURRENT BRANCH: {g['branch']} (upstream {g['upstream']}, ahead {g['ahead']}, behind {g['behind']})",
        f"LAST CONTEXT UPDATE: {now}",
        f"LATEST FROZEN TAG (git): {latest[0]} → {latest[1][:7]}",
        f"WORKING TREE: {tree}",
        END,
    ])
    ps = CTX / "PROJECT_STATE.md"
    text = ps.read_text()
    text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block,
                  text, count=1, flags=re.S)
    ps.write_text(text)

    lines = [
        "# GIT STATE (AUTO-GENERATED by tools/update_project_context.py — do not edit)",
        "",
        f"Generated: {now}",
        f"Repository: {g['remote']}",
        f"Branch: {g['branch']} · upstream {g['upstream']} · ahead {g['ahead']} / behind {g['behind']}",
        f"HEAD: {g['head']}",
        "",
        "## Tags (creation order)",
        "| Tag | Commit | Date |", "|---|---|---|",
        *[f"| {t} | {c} | {d} |" for t, c, d in g["tags"]],
        "",
        "## Recent commits",
        *[f"- {line}" for line in g["log"]],
        "",
        "## Working tree",
        ("clean" if not g["status"] else
         "Uncommitted paths (NOT part of any context commit; provenance must be "
         "checked before committing them):"),
        *[f"- `{s}`" for s in g["status"]],
        "",
        "## Lock / metadata files (research/*.json)",
        "| File | status field |", "|---|---|",
        *[f"| {n} | {s} |" for n, s in lock_statuses()],
        "",
        "## Result files referenced by RESULTS_CANONICAL.md (local, git-ignored)",
        "| Path | Exists on this machine |", "|---|---|",
        *[f"| {p} | {'yes' if ok else 'NO'} |" for p, ok in result_files()],
        "",
    ]
    (CTX / "GIT_STATE.md").write_text("\n".join(lines))
    print(f"updated PROJECT_STATE.md AUTO block and GIT_STATE.md at {g['head'][:7]}")


if __name__ == "__main__":
    main()
